using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;
using chamcong.WpfAdmin.Models;
using chamcong.WpfAdmin.Services;

namespace chamcong.WpfAdmin.Views
{
    public partial class CreateProductWindow : Window
    {
        private readonly ApiService _apiService;
        private readonly ProductsPage _parent;
        private ObservableCollection<ProductComponentModel> _components = new ObservableCollection<ProductComponentModel>();

        public CreateProductWindow(ProductsPage parent)
        {
            InitializeComponent();
            _apiService = new ApiService();
            _parent = parent;
            dgComponents.ItemsSource = _components;
            LoadCategories();
            LoadDistributors();
        }

        private async void LoadDistributors()
        {
            var distributors = await _apiService.GetAsync<List<DistributorModel>>("/api/distributors");
            if (distributors != null)
            {
                cbDistributor.ItemsSource = distributors;
            }
        }

        private async void LoadCategories()
        {
            var categories = await _apiService.GetAsync<List<ReferenceModel>>("/api/productcategories");
            if (categories != null)
            {
                cbCategory.ItemsSource = categories;
            }
        }

        private async void cbCategory_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (cbCategory.SelectedValue != null)
            {
                int categoryId = (int)cbCategory.SelectedValue;
                var parts = await _apiService.GetAsync<List<ReferenceModel>>($"/api/garmentparts/category/{categoryId}");
                cbGarmentParts.ItemsSource = parts;
            }
        }

        private void btnAddPart_Click(object sender, RoutedEventArgs e)
        {
            if (cbGarmentParts.SelectedItem is ReferenceModel part && int.TryParse(txtQtyPerProduct.Text, out int qty))
            {
                // Check if already added
                foreach (var c in _components)
                {
                    if (c.GarmentPartId == part.Id)
                    {
                        c.QuantityPerProduct += qty;
                        dgComponents.Items.Refresh();
                        return;
                    }
                }

                _components.Add(new ProductComponentModel
                {
                    GarmentPartId = part.Id,
                    GarmentPartName = part.Name,
                    QuantityPerProduct = qty
                });
            }
        }

        private void btnRemovePart_Click(object sender, RoutedEventArgs e)
        {
            if (sender is Button btn && btn.DataContext is ProductComponentModel model)
            {
                _components.Remove(model);
            }
        }

        private async void btnSave_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrWhiteSpace(txtProductName.Text) || 
                cbCategory.SelectedValue == null ||
                cbDistributor.SelectedValue == null)
            {
                MessageBox.Show("Vui lòng nhập Tên SP, chọn Danh mục và Nhà phân phối.", "Lỗi", MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }

            int.TryParse(txtQuantity.Text, out int quantity);
            decimal.TryParse(txtUnitPrice.Text, out decimal unitPrice);

            var requestData = new
            {
                ProductCode = "", // Will be auto-generated by backend
                ProductName = txtProductName.Text.Trim(),
                DefaultUnitPrice = unitPrice,
                Size = txtSize.Text?.Trim() ?? "",
                ProductCategoryId = (int)cbCategory.SelectedValue,
                DistributorId = (int)cbDistributor.SelectedValue,
                Quantity = quantity,
                Components = _components
            };

            bool success = await _apiService.PostAsync("/api/products", requestData);
            if (success)
            {
                MessageBox.Show("Tạo Sản phẩm thành công!", "Thông báo", MessageBoxButton.OK, MessageBoxImage.Information);
                _parent.LoadProducts();
                this.Close();
            }
            else
            {
                MessageBox.Show("Có lỗi xảy ra.", "Lỗi", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
    }
}
